### ISSUE TITLE
问下官方皮肤是 .ssf 的   这个.mssf要怎么安装 双击没有应用程序能打开 

### ISSUE THREAD

**Issue by eleanors** [xiaochunjimmy/Sogou-Input-Skin#1]

**Comment by xiaochunjimmy** [comment]
.mssf好像是官方针对苹果Mac版本输入法出的皮肤格式，理论上双击后就安装并且切换成功了。你是用的Mac吗？

**Comment by eleanors** [comment]
> .mssf好像是官方针对苹果Mac版本输入法出的皮肤格式，理论上双击后就安装并且切换成功了。你是用的Mac吗？

是Mac   输入法是搜狗五笔

**Comment by xiaochunjimmy** [comment]
这个是搜狗拼音输入法的皮肤😂

**Comment by xiaochunjimmy** [comment]
因为我没有用五笔输入法，所以实在不确定是不是可以。
https://pinyin.sogou.com/mac/skineditor.php 从这个页面来看，最下面有提到ssf升级为mssf，所以不清楚是不是只针对拼音，你试试从输入法的设置界面皮肤外观那块手动添加，看能成功不

**Comment by eleanors** [comment]
这个也试过  还是不行识别不了.mssf格式的   输入法是最新版本的

**Comment by xiaochunjimmy** [comment]
好吧，可能确实只支持拼音输入法

**Comment by J3n5en** [comment]
我这边是搜狗输入法（5.3.0.7499，提示了很多次，没升级.
双击也是打不开，不过去设置——外观 里面手动导入是ok的，遇到同样问题的可以试试。

![image](https://user-images.githubusercontent.com/10610925/58542387-1abac680-8230-11e9-93e5-eb87078b2331.png)

**Comment by Przeblysk** [comment]
楼上正解

**Comment by xiaochunjimmy** [comment]
> @J3n5en @Przeblysk 

感谢楼上提醒，我更新一下文档
