### ISSUE TITLE
请问收个候选字能否设置背景色？

### ISSUE THREAD

**Issue by someok** [xiaochunjimmy/Sogou-Input-Skin#10]
查了下 Windows 版搜狗有个属性是 `zhongwen_first_bk_color ` 用来搞这个的，不过 Mac 的没查到——Google 皮肤制作压根就没啥文章介绍，残念。 

类似mac 原生输入法效果：
<img width="476" alt="WX20190722-170811@2x" src="https://user-images.githubusercontent.com/1523082/61620421-5491d180-aca3-11e9-85f9-6dc5aecc88bf.png">

**Comment by xiaochunjimmy** [comment]
Mac端我是通过官网提供的制作工具制作的，工具中并没有提供高亮候选文字背景色的能力。不知道通
过 coding 的方式是否可以找到控制参数，我可以尝试找找

**Comment by dpcoo** [comment]
如果可以实现的话真的是太好了，背景色的方式要明显也要美观的多。
很期待你的结果。

**Comment by xiaochunjimmy** [comment]
这块我研究了一下，确实还没找到候选文字和高亮文字的背景色的设置。说一下我调研的发现，看是否可以给其他人提供思路：
1. 搜狗输入法皮肤编辑器本身不具备编辑候选字背景色的能力，而皮肤编辑器最终生成的是一个 .plist 格式的 XML 文件，色值是以 rgba 的方式以 XML 格式写的，但我从默认皮肤的 XML 文件中也没有找到相关的色值与配置参数信息。
2. Mac 输入法的卷轴模式在拉开卷轴的时候是可以看到两个颜色的，一个是当前行的背景色，一个是当前行选中文字的背景色，我原本想从这两个颜色的色值入手去搜索，但似乎他们用的是半透明色，这个就不太容易得对应色值了，如果是非透明色，可以用取色器得到结果。
3.我也尝试找过图片，看看这个背景色是不是用.9图弄的，也没找到。
我猜测这个候选字背景色可能需要专业的开发人员才能搞定了😔

**Comment by dpcoo** [comment]
周末愉快。
我之前也是类似思路，无果之后琢磨着如果Sogou支持，想必已经作为卖点写在更新列表里了。
通过你的确认看来单靠皮肤文件暂时是无法实现了。
感谢！

**Comment by xiaoyaozz** [comment]
https://pinyin.sogou.com/skins/detail/view/info/572006?rf=search&tf=p   请参考一下这个。
