### ISSUE TITLE
留言致谢，另外卷轴模式的机制太扯淡了

### ISSUE THREAD

**Issue by dpcoo** [xiaochunjimmy/Sogou-Input-Skin#11]
最初是不解卷轴模式下的错位问题，搜索到这里来的。
`.plist `文件检查很多遍，甚至在皮肤编辑器中新建皮肤，不改变任何参数保存，再与自带默认皮肤比对，也没有发现问题在哪里。
没想竟然是由皮肤ID白名单控制的😂
这有点过分了，不发布皮肤并通过审核的话，不是连测试也不行么？

故留言感谢解惑，且每个皮肤都那么漂亮！

我很好奇，你是怎么发现的？

附上我的皮肤效果：
![Input_theme](https://user-images.githubusercontent.com/1208366/62799511-929c4b80-bb13-11e9-9227-b6d8c4317fab.png)

**Comment by xiaochunjimmy** [comment]
感谢喜欢和支持，
卷轴模式白名单这个，倒不是我研究出来的，是咨询了一下官方的开发人员。
至于为什么白名单的皮肤才能有正常的卷轴效果，我猜可能是个BUG。
