### ISSUE TITLE
windows版本的能隐藏拼音输入吗

### ISSUE THREAD

**Issue by shishixiu** [xiaochunjimmy/Sogou-Input-Skin#12]
大佬您好 我想问下，windows能像苹果那样输入吗，就是拼音不显示在输入法的输入框里，输入框直接显示的候选字
像下面这张图一样
![图片](https://user-images.githubusercontent.com/47021717/62994875-ad165200-be90-11e9-93e5-c09504a22dab.png)

**Comment by jrfeng** [comment]
windows 版估计不支持。皮肤编辑器没有找到类似选项，输入法设置里也没找到类似选项。

**Comment by shishixiu** [comment]
好哒  谢谢大佬




------------------ 原始邮件 ------------------
发件人: "jrfeng"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 中午1:21
收件人: "xiaochunjimmy/Sogou-Input-Skin"<Sogou-Input-Skin@noreply.github.com>; 
抄送: "xiu"<2478874884@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiaochunjimmy/Sogou-Input-Skin] windows版本的能隐藏拼音输入吗 (#12)




windows 版估计不支持。皮肤编辑器没有找到类似选项，输入法设置里也没找到类似选项。

**Comment by S-Kee** [comment]
手心输入法可以实现这样的效果。
