### ISSUE TITLE
「石墨」for Windows 优化后丢失了阴影

### ISSUE THREAD

**Issue by SukkaW** [xiaochunjimmy/Sogou-Input-Skin#14]
https://github.com/xiaochunjimmy/Sogou-Input-Skin/commit/3bd55bffda94eda275993c47284ea653794f97b8 是正常的：

![image](https://user-images.githubusercontent.com/40715044/68397751-a1e07300-01ae-11ea-8501-5ffa7adc0606.png)

https://github.com/xiaochunjimmy/Sogou-Input-Skin/commit/b42415b7e2c1a28664e9636725ab5e8343d84fe7 以后阴影消失了：

shimo
![image](https://user-images.githubusercontent.com/40715044/68397836-c6d4e600-01ae-11ea-98a8-51626f0c2cb5.png)

---

看预览图是预期行为，但是还是希望有保留阴影的版本。

**Comment by xiaochunjimmy** [comment]
这个问题只能拜托 @jrfeng 了，不清楚他有没有时间处理

**Comment by jrfeng** [comment]
原来的 Windows 版皮肤是我自己参照设计图做的，所有有阴影效果，但是感觉不够还原，还有点丑。后来就把 Mac 版皮肤解压缩，用获取到的图片重新制作了皮肤。Mac 版皮肤解压缩后获得的图片是没有阴影效果的，如果你需要阴影效果的话可以加上。

@xiaochunjimmy 可能需要设计图的源文件，email: `jrfeng331@qq.com`

**Comment by xiaochunjimmy** [comment]
@jrfeng 原来如此，你是用什么设计软件的，Sketch 文件OK吗？

**Comment by jrfeng** [comment]
嗯，可以的

**Comment by xiaochunjimmy** [comment]
@SukkaW 咱们的小伙伴已经重新制作了，你看下还有什么问题吗？

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/68994275-13f63d80-08bc-11ea-8de4-bd89d401df44.png)

感觉有的地方比例不太对。。。

**Comment by jrfeng** [comment]
@SukkaW Sorry，应该皮肤背景没调整好，更换字体后会出现这个问题。现已修正，等合并后再下载试下吧。
