### ISSUE TITLE
皮肤的默认字体是什么字体？

### ISSUE THREAD

**Issue by Vergegung** [xiaochunjimmy/Sogou-Input-Skin#18]
尝试了几个字体，皮肤的显示都有问题，无法居中，不同字体的程度不同

**Comment by jrfeng** [comment]
windows 版皮肤的默认字体是 “宋体”

**Comment by Vergegung** [comment]
请问mac版本呢？我用了苹方跟思源黑，都在皮肤的靠上位置，没有居中😢

**Comment by jrfeng** [comment]
mac 版不清楚，需要问 @xiaochunjimmy

**Comment by xiaochunjimmy** [comment]
这个问题貌似不是字体的原因，是在某个搜狗输入法还是苹果系统更新的时候出现的，回头我重新手动调整下看看吧，一般情况下我们默认会用苹方字体。


| |
章萧醇
|
|


|


在2020年10月7日 08:45，Hugh Sun<notifications@github.com> 写道：

请问mac版本呢？我用了苹方跟思源黑，都在皮肤的靠上位置，没有居中😢

**Comment by Vergegung** [comment]
> 这个问题貌似不是字体的原因，是在某个搜狗输入法还是苹果系统更新的时候出现的，回头我重新手动调整下看看吧，一般情况下我们默认会用苹方字体。 | | 章萧醇 | | | 在2020年10月7日 08:45，Hugh Sun<notifications@github.com> 写道： 请问mac版本呢？我用了苹方跟思源黑，都在皮肤的靠上位置，没有居中😢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

非常感谢，这个皮肤太赞

**Comment by Vergegung** [comment]
> 这个问题貌似不是字体的原因，是在某个搜狗输入法还是苹果系统更新的时候出现的，回头我重新手动调整下看看吧，一般情况下我们默认会用苹方字体。 | | 章萧醇 | | | 在2020年10月7日 08:45，Hugh Sun<notifications@github.com> 写道： 请问mac版本呢？我用了苹方跟思源黑，都在皮肤的靠上位置，没有居中😢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不知道这个bug有没有修复啊？

**Comment by xiaochunjimmy** [comment]
问题已修复，使用 iMac 和 MacbookPro 测试后无问题（Mac OS：Big Sur）
