### ISSUE TITLE
Graphite 石墨能否有黑色主题的版本？

### ISSUE THREAD

**Issue by blackcater** [xiaochunjimmy/Sogou-Input-Skin#19]
![image](https://user-images.githubusercontent.com/9465551/109746827-ffed6100-7c10-11eb-9d03-3cebf797f40d.png)

我非常喜欢 Graphite 石墨这个主题。但是 Mac darkmode 下，希望有对应的黑色版本。

**Comment by xiaochunjimmy** [comment]
应该可以安排上

**Comment by blackcater** [comment]
> 试一下新增的皮肤 Carbon，由于我平时很少用深色模式，所以对于这款皮肤在深色模式下的可见性、可读性等还没有充分体验测试，您可以试一下，后期有反馈的话也可以给我说

🐂🍺

![image](https://user-images.githubusercontent.com/9465551/110503334-090d8f00-8137-11eb-82ba-e1bd8fd6efd1.png)
