### ISSUE TITLE
不支持非单行模式

### ISSUE THREAD

**Issue by zhangziang** [xiaochunjimmy/Sogou-Input-Skin#20]

**Comment by zhangziang** [comment]
在搜狗中的选项。
![screenshot-20210309-200722](https://user-images.githubusercontent.com/7501154/110468478-4d873380-8113-11eb-822e-4a780f239572.png)
其他皮肤取消选项后的效果。
![screenshot-20210309-200825](https://user-images.githubusercontent.com/7501154/110468523-61329a00-8113-11eb-81c7-b69ce9fe9796.png)
影响不大，单行模式也更清爽一些。

**Comment by xiaochunjimmy** [comment]
测试了一下，发现确实不支持非单行模式，不论勾选这个选项与否，都显示为单行模式。而且貌似搜索自带的一款默认输入法，也不支持该模式，可能是皮肤编辑器的能力限制，目前还没发现解决办法。问题先保留，看看是否有其他小伙伴知道解决方案。
