### ISSUE TITLE
很喜欢 Graphite 那一款，但是高度感觉有点高

### ISSUE THREAD

**Issue by ihewro** [xiaochunjimmy/Sogou-Input-Skin#21]
不知道是搜狗输入法的通病还是什么，候选区的单行高度都要比 Mac 原生输入法高很多

不知道是否可以提供原素材图片，这样就可以自己改一下图片尺寸再修改一下皮肤啦

**Comment by xiaochunjimmy** [comment]
您可以下载皮肤文件，然后使用搜狗输入法皮肤编辑器修改编辑，也可以重新上传自己的素材进行制作。

如果需要原素材的话，您可以下载皮肤后，将 .mssf 后缀改为 .zip，解压后会得到一个叫 skin 的没有后缀的文件，再给该文件添加 .zip 后缀解压，就得到皮肤的文件包了，里面会有当前皮肤用到的所有素材。

**Comment by ihewro** [comment]
好的感谢

**Comment by JinfengX** [comment]
贡献一个自己改的版本
[Graphite_edit.mssf.zip](https://github.com/xiaochunjimmy/Sogou-Input-Skin/files/14599953/Graphite_edit.mssf.zip)
