### ISSUE TITLE
Mac 使用 Tron.mssf 报错 Tron 皮肤不完善

### ISSUE THREAD

**Issue by my-Sakura** [xiaochunjimmy/Sogou-Input-Skin#23]
操作系统：
Darwin sakura 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
问题描述：
    双击 Tron.mssf 后，报错 'Tron 皮肤不完整‘
![image](https://user-images.githubusercontent.com/69021934/110619795-30199e80-81d3-11eb-8464-12372d68b44b.png)

**Comment by xiaochunjimmy** [comment]
这个问题还没找到原因，我这边自测是 OK 的；兄台这边其他皮肤 OK 吗？

**Comment by my-Sakura** [comment]
问题解决了。
我之前只下载了 Tron.mssf 文件，所以会报错，后面直接克隆整个 repo 就解决了
