### ISSUE TITLE
Windows 10 上字体不好看 😕

### ISSUE THREAD

**Issue by Puled** [xiaochunjimmy/Sogou-Input-Skin#24]
![capture](https://user-images.githubusercontent.com/30209777/110959900-2043bb00-8389-11eb-8d0c-479bd170f0bf.JPG)
如图，显示效果和 ![preview](https://camo.githubusercontent.com/f880a627272364c8fe5fc8ebdd2ccfc68a0591d15e8793c67186091dde6abda9/68747470733a2f2f63646e2e72656d697863646e2e636f6d2f696d6167652f67726170686974652d636f7665722e706e67) 的预览效果差别有些大呀。看起来不光滑，有很多像素点。

**Comment by jrfeng** [comment]
Windows 版皮肤的默认字体是宋体，皮肤的字体可以在输入法的设置里面更换。你列出的预览图是 Mac 皮肤版的，Windows 版皮肤的预览图在这里：[Windows 版预览图](https://github.com/xiaochunjimmy/Sogou-Input-Skin/blob/master/for_windows/skin_preview.md)

**Comment by chenghuayang** [comment]
我是繁體中文的使用者，英文部分我用 Input Mono，作者提供非商用免費的下載，對於 a、g、I、L 這些都可以調整成自己喜歡的格式，coding 也是用這個當做 display font。中文我用微軟正黑體（簡體是微軟雅黑）。整體配上去其實還不錯，推薦給你。

**Comment by EruDev** [comment]
win10 要怎么导入 .ssf 文件，换皮肤呀 @jrfeng @Puled

**Comment by Puled** [comment]
> win10 要怎么导入 .ssf 文件，换皮肤呀 @jrfeng @Puled

双击打开 .ssf 文件即可自动换皮肤。 请见[使用方法](https://github.com/xiaochunjimmy/Sogou-Input-Skin#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)。

另外可在 属性设置->外观->皮肤设置 中调整颜色，字体，大小等。

**Comment by EruDev** [comment]
> > win10 要怎么导入 .ssf 文件，换皮肤呀 @jrfeng @Puled
> 
> 双击打开 .ssf 文件即可自动换皮肤。 请见[使用方法](https://github.com/xiaochunjimmy/Sogou-Input-Skin#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)。
> 
> 另外可在 属性设置->外观->皮肤设置 中调整颜色，字体，大小等。

win10，没法双击打开 .mssf 文件呀。不好意思，前面说错了

**Comment by Puled** [comment]
> > > win10 要怎么导入 .ssf 文件，换皮肤呀 @jrfeng @Puled
> > 
> > 
> > 双击打开 .ssf 文件即可自动换皮肤。 请见[使用方法](https://github.com/xiaochunjimmy/Sogou-Input-Skin#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)。
> > 另外可在 属性设置->外观->皮肤设置 中调整颜色，字体，大小等。
> 
> win10，没法双击打开 .mssf 文件呀。不好意思，前面说错了

请下载[Windows 皮肤](https://github.com/xiaochunjimmy/Sogou-Input-Skin/tree/master/for_windows) 。

**Comment by EruDev** [comment]
> > > > win10 要怎么导入 .ssf 文件，换皮肤呀 @jrfeng @Puled
> > > 
> > > 
> > > 双击打开 .ssf 文件即可自动换皮肤。 请见[使用方法](https://github.com/xiaochunjimmy/Sogou-Input-Skin#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)。
> > > 另外可在 属性设置->外观->皮肤设置 中调整颜色，字体，大小等。
> > 
> > 
> > win10，没法双击打开 .mssf 文件呀。不好意思，前面说错了
> 
> 请下载[Windows 皮肤](https://github.com/xiaochunjimmy/Sogou-Input-Skin/tree/master/for_windows) 。

感谢，可以了 我沙比了 看错了- -

**Comment by Puled** [comment]
> 感谢，可以了 我沙比了 看错了- -

没事儿，安上就好。
![Facepalm](http://5b0988e595225.cdn.sohucs.com/images/20190120/9fc68a0ab3514a38b3b255ec102406ca.jpeg)
