### ISSUE TITLE
如果也给一个纯黑border的皮肤就好了, 二次开发之后, 去掉阴影更加简约

### ISSUE THREAD

**Issue by thinkerchan** [xiaochunjimmy/Sogou-Input-Skin#3]
谢谢作者提供这么好看的作品,  推荐用tinypng.com压缩png图片, 像这样的纯色图片, 压缩量可以到90%以上. 如果作者也用nodejs的话 可以npm装一个tinypic-cli, 就不用浏览器开tinypng.com了

**Comment by thinkerchan** [comment]
还有一个问题 cmd+shift+e进入英文模式之后 木有效果

**Comment by xiaochunjimmy** [comment]
感谢喜欢和反馈。
1.  后面有时间的话，我再出两款吧，确实没想到会有这么多朋友喜欢。到时候可以制作一个黑框无阴影的。压缩工具我也试一下。
2. 英文模式这个问题我也发现了，这个是受限于皮肤能力的。事实上搜狗官方出的皮肤，也没有（或者没办法）适配英文模式。
