### ISSUE TITLE
windows模式下，“V”键部分显示会超出皮肤边界，如下图

### ISSUE THREAD

**Issue by kunniang** [xiaochunjimmy/Sogou-Input-Skin#34]
![](https://zoer.us/file/6d03c6d7e2491df552e1e.png)
![](https://zoer.us/file/5386c696124f64681ea4f.png)

**Comment by pipipiper** [comment]
<img width="387" alt="image" src="https://github.com/xiaochunjimmy/Sogou-Input-Skin/assets/80835169/ed94606d-5406-4b39-8a6a-55d5c0eb7c61">
Mac也是如此

**Comment by xiaochunjimmy** [comment]
这个问题确实存在，但似乎不受我们控制，官方提供的皮肤编辑器能力有限
