### ISSUE TITLE
Windows 版制作有啥区别吗

### ISSUE THREAD

**Issue by ChromeBing** [xiaochunjimmy/Sogou-Input-Skin#4]
收藏

**Comment by xiaochunjimmy** [comment]
制作方法确实不一样，因为两个平台的输入法长得就不一样，导出的格式也不一样。
之所以只提供 Mac 版本，是因为这皮肤其实起初是为我自己设计制作的，而后才分享出来。我自己目前只有一台 Mac 电脑。如果你想自己尝试制作 Windows 版本的，可以前往官网皮肤主页，下载皮肤制作工具尝试一下，其实蛮简单的。

**Comment by ChromeBing** [comment]
我用的系统自带的




------------------ 原始邮件 ------------------
发件人: "章萧醇"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 中午12:58
收件人: "xiaochunjimmy/Sogou-Input-Skin"<Sogou-Input-Skin@noreply.github.com>;
抄送: "星宇"<1069502758@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xiaochunjimmy/Sogou-Input-Skin] Windows 版制作有啥区别吗 (#4)




制作方法确实不一样，因为两个平台的输入法长得就不一样，导出的格式也不一样。
 之所以只提供 Mac 版本，是因为这皮肤其实起初是为我自己设计制作的，而后才分享出来。我自己目前只有一台 Mac 电脑。如果你想自己尝试制作 Windows 版本的，可以前往官网皮肤主页，下载皮肤制作工具尝试一下，其实蛮简单的。
