### ISSUE TITLE
Mac 搜狗五笔不能使用该皮肤

### ISSUE THREAD

**Issue by shiyuan17** [xiaochunjimmy/Sogou-Input-Skin#5]
Mac搜狗拼音可以更改，搜狗五笔不能更改
![image](https://user-images.githubusercontent.com/4144030/58600967-4c2ba480-82b9-11e9-9e9f-fbfa0c23e58d.png)

**Comment by xiaochunjimmy** [comment]
是的，[这个朋友](https://github.com/xiaochunjimmy/Sogou-Input-Skin/issues/1) 也提到了这个问题，似乎确实不行，五笔输入法使用的还是ssf皮肤，拼音输入法使用的是mssf格式。
