### ISSUE TITLE
Windows 版预览图

### ISSUE THREAD

**Issue by jrfeng** [xiaochunjimmy/Sogou-Input-Skin#7]
**1. Tron 创：**

![1 Tron_preview](https://user-images.githubusercontent.com/17897996/59489017-b0528900-8eb3-11e9-8d24-713bbfdbd21e.png)

**2. Tangerine 橘色：**

![2 Tangerine_preview](https://user-images.githubusercontent.com/17897996/59489099-dc6e0a00-8eb3-11e9-8cbc-125d0d898fd8.png)

**3. Graphite 石墨：**

![3 Graphite_preview](https://user-images.githubusercontent.com/17897996/59489156-fc053280-8eb3-11e9-84e1-61734fe94f25.png)

**4. Boundary 界线：**

![4 Boundary_preview](https://user-images.githubusercontent.com/17897996/59489182-0de6d580-8eb4-11e9-98c9-62212f34195d.png)

**5. Matrix 矩阵：**

![5 Matrix_preview](https://user-images.githubusercontent.com/17897996/59489207-1b03c480-8eb4-11e9-81f3-923a09a97641.png)

**Comment by ddzy** [comment]
闻讯赶来, 非常不错, 感谢!

**Comment by xiaochunjimmy** [comment]
好棒，我刚刚更新了 Readme，你也可以根据需要提PR来修改，另外如果有需要相关素材的话我可以发你。


| |
章萧醇
|
|
woaichidapi@163.com
|
签名由网易邮箱大师定制


在2019年06月14日 14:53，jrfeng<notifications@github.com> 写道：

1. Tron 创：

2. Tangerine 橘色：

3. Graphite 石墨：

4. Boundary 界线：

5. Matrix 矩阵：

**Comment by jrfeng** [comment]
@xiaochunjimmy 嗯嗯，好的 :ok_hand: :ok_hand: :ok_hand:
